FROM node:18.16.1-alpine3.18 AS builder

WORKDIR /app

COPY package.json package.json

RUN npm install

EXPOSE 3000

COPY . .

RUN npm run build


FROM nginx:stable-alpine-perl

COPY --from=builder /app/out /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
